#!/usr/bin/env python
# encoding: utf-8

import os
import time

APPNAME = 'gatoss-client'
VERSION = time.strftime("%Y.%m", time.gmtime())

top	= '.'
out	= 'build'

def options(ctx):
	pass
	
def configure(ctx):
	pass
	
def build(ctx):
	ctx.stlib(
		source=ctx.path.ant_glob('*.c'), 
		target='gatoss-client', 
		includes='include',
		export_includes='include',
		use=['csp', 'gomspace'])

	if ctx.env.ENABLE_BINDINGS:
		ctx.shlib(source=ctx.path.ant_glob('*.c'),
			target = 'gatoss-client',
			includes = 'include',
			export_includes = 'include',
			use = ['csp', 'gomspace'])

